source 'https://rubygems.org'
ruby '2.6.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'

#Common Gems
gem 'rails', '5.2.4'
gem 'go-on-rails', '~> 0.4.0'
gem 'pg', '~> 0.21.0'
gem 'nokogiri'
gem 'httparty'
gem 'will_paginate'
gem 'jquery-ui-rails'
gem "select2-rails"
gem 'jquery-datatables-rails', :git =>'https://github.com/rweng/jquery-datatables-rails.git'
gem 'bootstrap-sass', '~> 3.4.1'
gem 'sassc-rails', '>= 2.1.0'
# gem 'zuora_api_oauth_alpha', '2'

#Front End Gems
gem 'simple_form'
gem 'peek'
gem 'peek-git'
gem 'peek-pg'
gem 'peek-performance_bar'
gem 'peek-redis'
gem 'peek-resque'
# Use SCSS for stylesheets
gem 'sass-rails'
gem 'bootstrap-toggle-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails'
# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-migrate-rails'
gem 'underscore-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# Rescue workers and delayed worker response
gem 'redis', '3.3.5'
gem 'redis-session-store'
gem 'redis-browser'
gem 'resque', :require => 'resque/server'
gem 'resque-scheduler'
gem 'resque-pool'
gem 'resque-web', require: 'resque_web'
gem 'listen'
gem 'turbolinks'
gem 'awesome_print'

group :production do
  gem 'unicorn'
  gem 'unicorn-worker-killer'
end

group :development do
  gem 'derailed'
  gem 'web-console'
  gem 'letter_opener'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'byebug'
end
